### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by niko-balanis** [BUStools/TENxBUSData#1]
#Leaving this here I hope this is not some simple issue that I am missing. I am unable to acess the #datasets in TENxBUSdata

I installed TENxBUSdata via devtools
install_github("BUStools/TENxBUSData")

fn <- TENxBUSData("./output", dataset = "pbmc1k")

#I get this error 
Error in .local(x, i, j, ...) : unknown key 'EH2650'

debug(TENxBUSData)
#Run through it until 
eh<-ExperimentHub()

library(stringr)
blah=str_sort(eh$ah_id,numeric=T)

#The final dataset in blah is EH2543 however we are requesting EH2650. This is why I think the bug is happening. It seems the data is not populated on Exepriment Hub. Please let me know if I am doing something wrong.

NikoB

**Comment by lambdamoses** [comment]
Which version of Bioconductor are you using? Now `TENxBUSData` is on Bioconductor 3.10, so is the data. Bioconductor 3.10 became the release version last week. Please make sure to install Bioconductor 3.10: `BiocManager::install(version = "3.10")`

**Comment by niko-balanis** [comment]
Yup so it was a simple issue.  Oddly using the default install which should install 3.10 still points to 3.9 for me.
BiocManager::install()


But ya using BiocManager::install(version="3.10") worked.

Thank you
